### ISSUE TITLE
GET /mavo/maps/mavo.js.map 404

### ISSUE THREAD

**Issue by alberto-marin** [mavoweb/mavo#206]
Hi, when working in local with [live-server](https://github.com/tapio/live-server) I always get a "not found" error with the map file. How can I fix it? Thanks

**Comment by LeaVerou** [comment]
How are you linking to Mavo?

**Comment by alberto-marin** [comment]
Locally.
[http://imgur.com/a/stzYK](url)

**Comment by LeaVerou** [comment]
Yeah, you have downloaded Mavo locally, but not the sourcemaps, so you're getting an error that they're not there. 

There are a few possible options here:
- Download the corresponding sourcemaps from http://get.mavo.io/
- Link to Mavo remotely
- Just ignore the error. You don't actually need the sourcemaps, since you’re not going to be debugging Mavo itself. You shouldn't be getting an error about this in the first place, and the fact that you are looks like a bug with live-server.
