### ISSUE TITLE
"Unexpected token ; in expression" error in expression.js when string contains [Square Brackets]

### ISSUE THREAD

**Issue by jop3** [mavoweb/mavo#210]
When the html on a website that implements Mavo contains square brackets [ ] an error is thrown in expression.js, line 24.

The square brackets are also filtered away from the resulting html that is shown in the browser. Double square brackets [[ ]] have to be used to display the original brackets. The tag that contains the brackets does not have a "property" set, and should not be changed by Mavo.

Example:

    <div>
       [INSTÄLLT] Vuxenträning
    </div>

**Comment by LeaVerou** [comment]
By default, Mavo picks up anything inside square brackets as an expression. That doesn't require any `property` attributes. You can disable this by specifying `mv-expressions="none"` on the `<div>` to disable expressions altogether, or something like `mv-expressions="{{ }}"` to change the syntax from square brackets to something else (double curly brackets in this example).

That said,

- There should be no error, just an information-level message in the console
- Since this is not a valid expression, it should not be processed

Is this example online somewhere so I can verify that the behavior is as expected?

Thanks.

**Comment by jop3** [comment]
Thank you for the information, the mv-expressions setting did the trick. You are absolutely right that this does produce only a console informational message, i mistook it for an actual error while debugging. Could perhaps the information about mv-expressions be added to the console message for easier fixing?

**Comment by LeaVerou** [comment]
> Could perhaps the information about mv-expressions be added to the console message for easier fixing?

Great idea!

**Comment by jop3** [comment]
Not an error, just a configuration issue. Closing.

**Comment by LeaVerou** [comment]
I just pushed a fix that should address both issues:

- Brackets won't be "eaten" for invalid expressions
- `mv-expressions="none"` is suggested in the console message.

Thanks!
