### ISSUE TITLE
Date disappears if focus lost while date incomplete

### ISSUE THREAD

**Issue by svgeesus** [mavoweb/mavo#226]
Browsers with sucky implementations of the html5 time element (for example, making the user type in an ISO date instead of selecting from a calendar) can generate invalid dates if focus is lost from the editing popup part way through editing.

The Mavo regexes then generate empty strings, so there is nothing to click on and the whole date unavailable for editing unless first resurrected by making the attribute contents valid through dev tools

**Comment by LeaVerou** [comment]
Fixed this by making sure `year()` will work with incomplete dates which should help with the majority of cases.
It should be noted that since this bug was reported, the browser support landscape for date inputs has changed quite significantly, making this much lower priority than it originally was. Now all browsers support date inputs, and I had to go back 8 (!) Firefox versions to reproduce this and work on it.
