### ISSUE TITLE
Add mv-storage-type to override storage backend type

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#240]
Some storage backends need a URL but their type cannot be determined via the URL alone (e.g. SOLID, PHP). Other times we want to use a storage backend with a different URL (e.g. Enterprise Github). Therefore, there needs to be an override for which backend to use, probably named `mv-storage-id`.

**Comment by karger** [comment]
maybe mv-storage-type?

**Comment by LeaVerou** [comment]
Ah yeah, I think that’s better!

**Comment by joyously** [comment]
I was considering a backend that used a WordPress site for storage. But then I thought that could mean two different things: a file or a database entry. Would that be two different backends, or a type indicator for one backend? 
Since you are referring to a URL, maybe call that a URL, not a type. For my use case, I would need a URL and a type?

**Comment by LeaVerou** [comment]
> I was considering a backend that used a WordPress site for storage. But then I thought that could mean two different things: a file or a database entry.

That would be amazing!

> Would that be two different backends, or a type indicator for one backend?

Two different backend ids, though they can still share code.

> Since you are referring to a URL, maybe call that a URL, not a type.

`mv-storage` is the URL (when a URL makes sense), the proposed attribute here would accept values like `github`, `dropbox`, `wordpress` etc, not URLs.

> For my use case, I would need a URL and a type?

Yes, because it cannot be figured out from the URL. There is nothing unique in a Wordpress URL that means Mavo can be certain it's a WP URL without making any requests. Contrast that with Github or Dropbox for example, which is obvious just from the URL format.

**Comment by joyously** [comment]
I guess I'll have to wait to see how you change the code, because this doesn't make sense to me.
The existing storage object already has `id` with values like `github`, `dropbox`, `firebase`. 
`mv-storage` is an attribute, isn't it? with values like you are saying go in the new one? But I don't see where a URL goes (they are currently hardcoded).

> Yes, because it cannot be figured out from the URL. There is nothing unique in a Wordpress URL that means Mavo can be certain it's a WP URL without making any requests. 

Yes, since wordpress.com doesn't allow scripts in user content, the Mavo app can't be there. I don't know if the REST API can be used to interact with the database there or not. I have no experience with that. I was referring to wordpress.org, which means that the URL could be anything. But reading up on the WP REST API, the docs referred to security risks of storing JSON because the object could be anything and it is created (not sure when).

**Comment by LeaVerou** [comment]
> I guess I'll have to wait to see how you change the code, because this doesn't make sense to me.
The existing storage object already has `id` with values like `github`, `dropbox`, `firebase`. `mv-storage` is an attribute, isn't it? with values like you are saying go in the new one? But I don't see where a URL goes (they are currently hardcoded).

I think you might be confusing the JS internals with the HTML syntax that people write to use Mavo. When you’re not writing JavaScript, the `mv-storage` attribute is how you set where your app data will be stored. Today, it's typically a URL or a keyword, such as `https://github.com/leaverou/data/foo.json` or `local`. The `mv-storage` attribute serves two purposes: It tells Mavo **where** the data is stored, as well as **which** storage backend to use for handling them. What I'm saying is that sometimes these two bits of information need to be separate, because one cannot be inferred from the other.

> Yes, since wordpress.com doesn't allow scripts in user content, the Mavo app can't be there.

The Mavo _files_ cannot be linked from there, a Mavo app is just HTML so it can totally be there. In fact, I use Mavo apps for displaying my list of talks, on my Wordpress site: http://lea.verou.me/speaking/

**Comment by karger** [comment]
Another good reason for this separation is if for example you want to 
use a standard storage location (dropbox) but a nonstandard storage 
format (maybe you want to interact with a csv that is used by some other 
application).

**Comment by LeaVerou** [comment]
> Another good reason for this separation is if for example you want to use a standard storage location (dropbox) but a nonstandard storage format (maybe you want to interact with a csv that is used by some other application).

No, that's a format and is handled separately from storage adapters. If you provide a CSV URL for example, it will automatically use the CSV format. Or you can explicitly say `mv-storage-format="csv"` if your file has a nonstandard extension.

Read more about formats here: http://mavo.io/docs/formats/
