### ISSUE TITLE
Negative numbers are converted to positive numbers

### ISSUE THREAD

**Issue by Dsan10s** [mavoweb/mavo#279]
If an array has negative values and is used in an expression, the expression gets parsed to an array with only positive values (the negative values are turned positive).

**Comment by LeaVerou** [comment]
It's easy to see what's happening by running the following in the console:

```js
> Mavo.Script.serialize(Mavo.Script.parse("[-1, +2]"));
< "[subtract(1), add(2)]"
> Mavo.Functions.subtract(1)
< 1
```

This must have existed since 0579f87c474255b0530020a8584a939bc3f062ca.
Unary operators were not properly rewritten before then, so the fact that `subtract()` was not doing the right thing when called with 1 argument was masked.
Should be an easy fix.
