### ISSUE TITLE
Provide CSS framework

### ISSUE THREAD

**Issue by mycaule** [mavoweb/mavo#322]
Have you been thinking about providing a lightweight set of _CSS_ directives like _Twitter Bootstrap_ inside `mavo.css`? Is this this mandatory to run a _Mavo_ app ?

[_W3-CSS_](https://www.w3schools.com/w3css) is cool.

If the user don't know anything about CSS, he has to do a lot of research before starting to prototype his app. He doesn't want to learn _SASS_, _Less_, _Stylus_ or whatever to ensure browser compatibility.

**Comment by LeaVerou** [comment]
Why not use Bootstrap or any other CSS framework? The ecosystem is full of great CSS frameworks, why would we provide yet another one?

**Comment by mycaule** [comment]
To avoid the "Do It Yourself" approach.

**Comment by LeaVerou** [comment]
But there is no optimal combination — literally any CSS framework should work (and if not, I'd consider it a bug).
So, if you want a boilerplate, why not use e.g. a Bootstrap boilerplate? :)

**Comment by mycaule** [comment]
I think you can use mavo without mavo.css.
The `mv-bar`stuff can be implemented directly in HTML. There are also lighter alternatives to Bootstrap. You can also toss out the custom time picker and input you have in your repo because they are opiniated.

**Comment by LeaVerou** [comment]
> I think you can use mavo without mavo.css.

You are free to do so, but I cannot guarantee that things will work.

> The mv-barstuff can be implemented directly in HTML, create, edit, save, delete buttons could be declared manually.

[You can do that as well](https://mavo.io/docs/ui#bar).

> There are also lighter alternatives to Bootstrap. 

And you are free to use them. Bootstrap was just a suggestion, since you said you wanted to use a CSS framework and Bootstrap is the most popular one.

> You can also toss out the custom time picker and stretchy input you have in your repo because they are opiniated. 

There is no custom time picker, I’m just using the default HTML time picker. I guess HTML is too "opiniated" [sic]?
Not sure how Stretchy is "opiniated" [sic], it only operates on inputs that Mavo generated.

Also, didn’t you say you’re not going to "help anymore" in another thread? On the other hand, you only said you wouldn't help, not that you would stop speaking, so I guess this does hold true…

**Comment by amexperts** [comment]
Lol. Nice reply.

**Comment by mycaule** [comment]
That's what I did it worked.
