### ISSUE TITLE
Math comparison operators don't combine if different

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#347]
I.e. while `1 < 2 < 3` is correctly interpreted as `1 < 2 and 2 < 3`, this does not happen with `-3 <= -3 < 1` which returns false, since it's interpreted as `(-3 <= -3) < 1 => true < 1 => 1 < 1 = false`

**Comment by betaveros** [comment]
The converse problem also occurs: identical comparison operators are chained even if explicit parentheses should prevent them from doing so. For example `(5 > 4) > 3` is actually interpreted as chained `5 > 4 > 3`, which is True.

I don't think we can make comparison operators chain properly if we only use jsep as-is because it throws away parenthesization information after parsing, so that `(5 > 4) > 3` and `5 > 4 > 3` give identical parse results.

**Comment by LeaVerou** [comment]
Damn, that's right. Well spotted.
OTOH I'm not sure that's a significant problem for comparison operators. (5 > 4) is `true`, so then `(5 > 4) > 3` would be `true > 3` which is nonsensical to non-programmers who wouldn't think of `true` as `1`.
Thankfully, it does not seem to occur with other operators, where it would be a real problem. For example `1 / (2 / 3)` is correctly 1.5, and not 0.1666667 (1 / 2 / 3).
