### ISSUE TITLE
Mavo as editor only?

### ISSUE THREAD

**Issue by stalcer** [mavoweb/mavo#377]
Is it possible to load and use Mavo only as a content editor?

I wanna to try to parse JSON data files on server side and generate pages with content from them. This approach can solve a problem with search engines visibility (which truly exists) and page content will be visible to users immediately without Mavo loading waiting time. In this case, I want to load Mavo only after admin authentication: login -> edit -> save. That's all.

Is this scenario possible ever?

**Comment by LeaVerou** [comment]
Search engines (at least Google) do execute JavaScript. Mavo includes Chrome 41 support for this very reason (Googlebot is basically Chrome 41 in terms of JS support).

But to answer your question, yes, I believe that should work, though since it hasn't been done you may find some issues when you try it (please report them so we can fix them!). Mavo works on existing rendered HTML, as long as that HTML uses the right Mavo attributes. You may find this helpful: https://plugins.mavo.io/plugin/importhtml
Even though it's designed for importing data from HTML, it will also be useful for mass-applying Mavo attributes via CSS.

Hope this helps, let us know how it went!
