### ISSUE TITLE
Set a property label (placeholder) via aria-label

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#485]
TIL: a placeholder text for properties are controlled by the `aria-label` attribute that Mavo adds automatically. By default, it is a human-readable value of a property (if I am not mistaken). I tried to change it, and to my joy, it worked when I switched to edit mode of the app. But then I clicked the property to change its value, the placeholder text changed to the text generated by Mavo, and I couldn't control it anymore. I was expecting `aria-label` to set the label! But as I learned it's not the case now.
My reduced testcase is [here](https://codepen.io/dsharabin/pen/VggPYV?editors=1100).
I am sure, this feature would be useful. Especially concerning the issues: #455 and #456. Localization is the theme really close to my heart. 😃

**Comment by LeaVerou** [comment]
Testcase: https://codepen.io/leaverou/pen/jdReRR?editors=1100

**Comment by LeaVerou** [comment]
Hi @DmitrySharabin,

I was planning to defer this until after v0.2.0 since I'm avoiding adding new features to it at this point, but it was too easy to implement.

Do note that even though it supports expressions, the expression will be evaluated the first time the property is edited (e.g. see custom2 in my testcase). Future expression changes however will not be picked up (as you can see in custom3 in the testcase)).

I'm gonna look into making it dynamic, but that **may** have to wait.

**Comment by LeaVerou** [comment]
I just pushed a fix that makes it dynamic too :)

**Comment by DmitrySharabin** [comment]
> I just pushed a fix that makes it dynamic too :)

Oh, yes! I know that filling when you can't stop until it's done and is perfect. 😂

Thanks, Lea! That's 🔥!
