### ISSUE TITLE
Expression in mv-source/mv-storage wipes local data

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#489]
Testcase: https://codepen.io/leaverou/pen/PVLeEW?&editors=1100#0

Basically, the expression `[repo]` in `mv-source` forces a re-render of the data, which makes the `repo` property return to its default (template-derived) value, even though there's no such property in the data.

**Comment by karger** [comment]
If we are looking at such reflexive evaluations, I wonder if

mv-multiple="[mult]" lets you dynamically change whether a property is 
multiple?
mv-value="[[expr]]" lets you dynamically modify the expr that is 
evaluated?
mv-format="[format]" lets you dynamically specify the format of a data 
file?
property="[pname]" let you dynamically pick the name of a property?

------ Original Message ------

**Comment by LeaVerou** [comment]
@karger One day! However this issue is not about making `mv-source` and friends dynamic, it already is.

**Comment by karger** [comment]
Having an expression in your mv-source that depends on data *inside* the 
mv-source raises all sorts of questions, because as soon as you change 
the inner data you change the repo, which means that the expression 
immediately changes its value, which means that the new identified repo 
is no longer (necessarily) the correct one.   Do you then proceed to 
load a third repo, fourth, add infitum?  It would be easy to end up with 
circularity between two repos that point at each other.

I'm not saying we need to prevent this, but perhaps it is worth just 
describing this as a bad idea with unpredictable consequences, instead 
of trying to work out a consistent solution.

**Comment by LeaVerou** [comment]
Not sure why it's a bad idea. In every use case of this, the expression setting the storage/source URL doesn't depend on data from the storage/source URL. Either it's properties that are not present in that data, or data independent (e.g. a URL expression).
Of course it can lead to circularity and loops, everything sufficiently powerful can.
