### ISSUE TITLE
Provide way for easy comparison with date intervals

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#493]
(everything below that refers to months applies to all the date intervals, days, weeks, hours, etc)

Right now, if we want to compare whether the difference of two dates is e.g. larger than 2 months, we have to painfully write something like `foo > 2 * 30.4 * 24 * 60 * 60 * 1000`.

We have the `months()` function that accepts a number of milliseconds and converts it to months, but not the opposite. 

Perhaps we could repurpose the `months()` function to return the number of ms for 1 month if used with no argument. Then the comparison would become `foo > 2 * months()` which is not too bad!

Or maybe we can come up with some fancy syntax. E.g. `foo to months` (ms to months) and `foo months to ms` (months to ms). Though that's trickier to implement so it may have to wait.

**Comment by LeaVerou** [comment]
Tests: https://test.mavo.io/datetime.html#date-units-to-ms

**Comment by karger** [comment]
I'd suggest looking at SQL to see what it does with dates.  A quite rich set of conversions between dates, times, time intervals, and numbers.  I think they just overload the comparison and sum and difference operators so that it is meaningful to compare date objects.  Of course this requires a type system that knows these three things are different.

https://www.postgresql.org/docs/9.1/functions-datetime.html

**Comment by LeaVerou** [comment]
Wouldn't spreadsheets be a better comparison?

Btw Mavo already overloads subtraction, and has for years. Now that we have these, we could also overload addition, so you could do things like `date + 2 * months()`!

**Comment by karger** [comment]
Spreadsheets are inadequate with dates.  They treat date as a format rather than a type.  if you enter a date it is immediately converted to a number (ms since 1970) and any reference to it sees a number and has no idea that it's a date.  Which can lead to some rather frustrating errors.  And, spreadsheets have no type *or* format for representing time intervals.
