### ISSUE TITLE
split function listed in doc but not in stable version

### ISSUE THREAD

**Issue by andreasplesch** [mavoweb/mavo#519]
Apologies for the fuzzy title but I am at a loss:
https://impossible-hydrofoil.glitch.me/ does not work
but
https://codepen.io/anon/pen/mgrZQg?&editors=1100#0
does.
They look the same to me ?
[doc issue, changed title]

**Comment by DmitrySharabin** [comment]
Hi there!
It seems to me it's because you use different versions of Mavo: in codepen, by default, is used the latest one (that is currently under development), but in your project, you use the stable one.
To fix your problem just use these lines of code in the head of your document:
`<script src="https://dev.mavo.io/dist/mavo.js"></script>`
`<link rel="stylesheet" href="https://dev.mavo.io/dist/mavo.css">`

**Comment by andreasplesch** [comment]
Ok, I found it:
https://github.com/mavoweb/mavo/commit/a89e863daa65e80e73f6e55e0e63b9812b08ced
It is listed in the documentation of all expression functions:
https://mavo.io/docs/functions/#split
It would be useful to add an asterisk or something to those functions which are not available in the stable version, until they get stabilized. Just a thought, I know it is hard to manage multiple versions.
I suppose the dev version is really the prerelease version at this point.

**Comment by andreasplesch** [comment]
Since I found #520, I think I will stick to the stable version and just use js in the expression for splitting.

**Comment by LeaVerou** [comment]
> I suppose the dev version is really the prerelease version at this point.

Correct! The stable version is so old we strongly recommend using the dev version until a new stable is released (which should be very soon).

**Comment by LeaVerou** [comment]
I'm gonna go ahead and close this, since it's not technically a bug.
I do agree that we should list versions in the docs (we do for some things, but not others). Perhaps we need an issue in the mavo.io repo to track this, since it's about the website and not Mavo per se.
