### ISSUE TITLE
move(collectionName, totalCountProperty) deletes items instead of moving to the end!

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#539]
`move(collectionName, totalCountProperty)` (where totalCountProperty is defined as `[count(collection)]` outside the collection) seems to make the item disappear instead of moving it to the end of the collection. 

Oddly, using `0 + totalCountProperty` fixes it, so it looks like it could be a type-related issue.

Testcase: https://codepen.io/leaverou/pen/YoEdMz?editors=1000

**Comment by LeaVerou** [comment]
That was much easier to fix than I thought it would be!
Turns out it wasn't a type issue at all. The bug was that the collection to move to was determined before the function parameters had been completely disambiguated, so if the signature was `move(item, index)` and index pointed to a Mavo node, Mavo would try to extract which collection to move to based on which collection `index` belongs to (in this case, none, hence the weird behavior).
The reason `0 + count` worked was that then the result didn't have a reference back to the property, so Mavo didn't get confused. Nothing to do with types!
