### ISSUE TITLE
Minified version of Mavo CSS file

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#540]
I noticed one thing but haven't told about it earlier: when we download the compressed version of Mavo, we get minified version only for the JS file. What if we could have corresponding CSS file also minified? Does it make sense? We could have not only two more harmonized file names—mavo.min.js and mavo.min.css—but also save some kilobytes of traffic. 😀

**Comment by LeaVerou** [comment]
Yeah, I guess I didn't do that because the CSS file isn't as big (and savings from CSS minification tend to be smaller than for JS). But I guess at this point it might make sense.

**Comment by karger** [comment]
How much would it save?  Since day someone will wish it weren't minified

**Comment by LeaVerou** [comment]
> How much would it save?

Not sure, I'll need to calculate. @DmitrySharabin, do you want to try that and tell us what the savings are? Any up-to-date CSS minifier would do.

> Since day someone will wish it weren't minified

I can't parse this

**Comment by DmitrySharabin** [comment]
Today I tried this [site](https://cssminifier.com/) to minify Mavo CSS. It gave me the minified version of size 19 898 bytes (~20Kb). Compare to the not minified version which is 24 068 bytes (~25Kb) we have the version which is ~17% smaller.

**Comment by DmitrySharabin** [comment]
[cssnano playground](https://cssnano.co/playground/) gives us an almost identical result. It's not 65% of course. But why not if we can?

**Comment by DmitrySharabin** [comment]
I've nearly forgotten: if we choose not minified version instead of the minified one we get +20% filesize.

**Comment by LeaVerou** [comment]
Thank you for looking into it Dmitry! I'd be fine with this, though I'd rather leave it up for grabs for a while, since this is a good first PR for anyone who might want to get involved.

Steps to implement:

- `npm install X --save-dev` where X is a good CSS minifier that works with gulp
- Add a new minify-css task to the gulpfile and make sure it runs AFTER `sass` in the default task and operates on `mavo.css`.
- Send a separate PR to the mavoweb/mavo.io repo to modify the URL generator so that it adds a `.min` to the CSS file as well when minified is selected.

**Comment by DmitrySharabin** [comment]
The corresponding functionality is implemented. So there is no need to leave this issue opened anymore. We have one issue less. Yay! 😀
