### ISSUE TITLE
[github] Allow overriding Github params via attributes

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#665]
Leftover work from #657
Blocked on #664

Now that we can provide metadata to the backend via attributes, we should also support both when this makes sense. For example, for Github we should be able to override the params that are extracted from the URL through these attributes, whether they are provided in the URL or not. 
Any data not provided should default to the existing defaults.

E.g. these should be all valid:

```html
<E mv-storage="https://github.com" mv-storage-username="leaverou" mv-storage-repo="mavoweb" mv-storage-path="data.json">
<E mv-storage="https://github.com/karger/otherrepo" mv-storage-username="leaverou" mv-storage-repo="mavoweb" mv-storage-path="data.json">
<E mv-storage="https://github.com/leaverou"mv-storage-repo="mavoweb" mv-storage-path="data.json">
<E mv-storage="https://github.com" mv-storage-username="leaverou" mv-storage-path="data.json">
```

This is trickier than it seems due to how `Mavo.Backend.Github.parseURL()` is implemented, where some values depend on other values.

**Comment by DmitrySharabin** [comment]
I need to ask one question to be sure that I get everything correctly: by `mv-storage-path` you mean `mv-storage-filename` (according to your examples)? Since we already have the `filepath` property and can override it via `mv-storage-filepath`, and we construct `path` using `filepath` and `filename`.

Please correct me if I get something wrong.

**Comment by LeaVerou** [comment]
Ideally, a user should be able to provide either `filename`, `path`, or `filepath`.
