### ISSUE TITLE
Make mv-edit live

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#703]
Now that we removed the ability to provide separate editors per property by nesting them (#692), we should make the `mv-edit` attribute "live" to cater to these these use cases.

**Comment by LeaVerou** [comment]
Question that came up as I was working on this: What should happen if the selector in `mv-edit` matches nothing?
Should the property not be editable, or should it get the default editor?

**Comment by DmitrySharabin** [comment]
I wonder whether Mavo authors expect it to be more forgiving or more “strict”? :)

I personally would like to know that I do something wrong asap. And if a property isn’t editable, then it might be because Mavo didn't recognize it, e.g., there is a typo in the word “property.” Or the selector in `mv-edit` matches nothing. And I can't know from the very beginning which of these cases caused the issue.

But if I get the default editor, I can guess that something is wrong with the selector in `mv-edit`, i.e., I have only one thing to check.

So I vote for the default editor.
