### ISSUE TITLE
Move Dropbox backend to a plugin

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#711]
Given that this is not particularly commonly used, it's not ideal that every Mavo app carries this code.

**Comment by DmitrySharabin** [comment]
@LeaVerou 

Let's close this issue and make our beloved Mavo a bit smaller (but no less powerful). :)
Here are PRs in different repos:

- https://github.com/mavoweb/mavo/pull/784
- https://github.com/mavoweb/plugins/pull/103
- https://github.com/mavoweb/test/pull/39

Could you please review them so that I could remove the corresponding section from the docs?

**Comment by DmitrySharabin** [comment]
Oh, excellent point! Will do exactly that. Thanks!

**Comment by LeaVerou** [comment]
Maybe also say "To migrate your existing app to use the new plugin, use `mv-plugins="dropbox"` anywhere in your markup.

**Comment by DmitrySharabin** [comment]
Done!

https://mavo.io/docs/storage#dropbox

If there's something I did wrong please feel free to correct me.
