### ISSUE TITLE
Remove mv-like

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#733]
Our codebase has grown quite a lot in size and complexity, making even the most trivial of changes very difficult.

I cannot count the number of times lately that I've started working on a change, then gave up and reverted because it introduced too many regressions and hard to debug issues.

This is bad.

So as I'm working, I'm keeping an eye out for things we could remove that would remove a lot of complexity while not affecting many existing Mavo apps. 

Right now, `mv-like` has the biggest ratio of value_if_removed / value_if_kept

It's a buggy feature that was never documented or properly fleshed out and it increases complexity **a lot**. It's [not used much](https://github.com/search?l=HTML&q=mv-like&type=Code), and hopefully it will be easier to implement in the future anyway. The existing use cases can be worked around by just copying and pasting and using `mv-initial-items="0"`, except the ones that are infinitely recursive, which are very few.

What do you think @karger @DmitrySharabin?

**Comment by karger** [comment]
How many of the used cases (several are yours) can be eliminated wth the 
workarounds you suggest?  If it's not really needed, I think removing is 
fine.

**Comment by LeaVerou** [comment]
All except turtle, which is recursive. But that demo was never published anywhere.

**Comment by DmitrySharabin** [comment]
I agree that we can remove it. I have only one private pen where I gave this feature a try. And since I couldn’t decide whether my pen was useful to anyone using Mavo, I left it private. I was trying to model a hierarchical structure of goods for a shop if you are interested. 😉

I suppose this feature should make it easy to add comments (and their threads) to a site. But since we can use Disqus for it with ease, it’s not a problem anymore.

**Comment by LeaVerou** [comment]
Btw this was the change needed to remove `mv-like` from forkgasm: https://github.com/LeaVerou/forkgasm/commit/f5b123ce4e5a498ece8897843637180bdfa989c4
