### ISSUE TITLE
Moving items between two collections is broken

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#738]
See the [Decisions](https://mavo.io/demos/decisions/) demo.

It looks like that regression was introduced by this commit: https://github.com/mavoweb/mavo/commit/2f154fc6f24c7a60cc0d6a85a17b3e5d01906923.

**Comment by LeaVerou** [comment]
In general Dragula is pretty much unmaintained at this point, so if you have any spare cycles and want to look for a good replacement, it would be time well spent!

**Comment by GalinhaLX** [comment]
Hi,

I came to an unexpected case, where moving from one list to another, WORKS 

Use case: It can be used to propose a list of options, that you can drag to content user list (except property is flag as target, instead keeping as initial)

(hope it can help to solve the issue)

[https://codepen.io/GATIGA/pen/zYEypbV](https://codepen.io/GATIGA/pen/zYEypbV)

**Comment by LeaVerou** [comment]
> It looks like that regression was introduced by this commit: [2f154fc](https://github.com/mavoweb/mavo/commit/2f154fc6f24c7a60cc0d6a85a17b3e5d01906923).

My apologies for the cryptic commit message :( I can't even figure out what I was trying to do, and because the logic was changed in the same commit that inlined the `adopt()` function, it's hard to tell what actually changed.
If you have some cycles to investigate, you could inline the original `adopt()` function, then gradually make the changes in the commit and see when the regression is introduced. Like a sub-commit git bisect of sorts 😁

**Comment by DmitrySharabin** [comment]
Interestingly, dragging items between collections works fine if it is one-directional (see [here](https://codepen.io/dmitrysharabin/pen/ExGvBwM) and [here](https://codepen.io/dmitrysharabin/pen/mdaMgQK)). 🤔

However, it looks like we have [another bug](#969) here if I get our docs correctly.

**Comment by LeaVerou** [comment]
Btw this is the last remaining issue before we can release v0.3.0! Can we make it happen?
@DmitrySharabin you were doing some investigating, are you any further forward than https://github.com/mavoweb/mavo/issues/738#issuecomment-948934551 ?
