### ISSUE TITLE
Provide a way for a backend to signify that data has changed

### ISSUE THREAD

**Issue by DmitrySharabin** [mavoweb/mavo#755]
As @LeaVerou mentioned in our conversation, there is currently no way for a backend to signify that data has changed.

She is thinking, architecturally, backends should have the ability to signify that data has changed, and it should be Mavo's responsibility to handle that (or not).

**Comment by LeaVerou** [comment]
The way I'm currently thinking of dealing with this is to make `Mavo.Backend` inherit from `EventTarget`. and fire events on that (including the existing `mv-login` and `mv-logout` events which would be better suited to events on the backend object instead of events on the Mavo root, and would help decouple Mavo a bit more from the storage code (which down the line we want to release as a separate library).

**Comment by LeaVerou** [comment]
Any ideas about the name of the event?

* `mv-backenddatachange`
* `mv-datachange`
* `mv-datastale`
* `mv-remotedatachange`

Any other ideas?

**Comment by DmitrySharabin** [comment]
Do I understand correctly that we already have the `mv-change` event for local data changes? What if we rename it to `mv-localdatachange`, so that it plays smoothly with  `mv-remotedatachange` (if we decide to choose this name)?

And yes, I vote for `mv-remotedatachange` as you probably guessed. :)

**Comment by LeaVerou** [comment]
Nah, I don't want to make *both* of them unwieldy just so they're similar. They're for completely different things. My quip with `mv-remotedatachange` is that it's not always remote data (e.g. think of the Element or Local backends) but I suppose that's a rather small fraction of uses.

**Comment by karger** [comment]
mv-storage-change?

**Comment by LeaVerou** [comment]
> mv-storage-change?

It's not necessarily storage. It could be the `mv-source` backend that changes, or the `mv-init` one.
