### ISSUE TITLE
bug: remote loaded json with mv-init + mv-list/mv-list-item embedded in DOM by default

### ISSUE THREAD

**Issue by davemo** [mavoweb/mavo#797]
## Context

Hi! I'm trying to learn Mavo by rewriting a JS app I had previously built but I seem to have hit a bug that I can't reconcile.

I'm not exactly sure what's causing this, but I cannot seem to get `mv-init` or `mv-source` and `mv-list`/`mv-list-item` to work without embedding JSON in the DOM. 

## Test Case

In this isolated [test case](https://codesandbox.io/s/stoic-framework-qsd08?file=/index.html) I'm seeing the same buggy behaviour as happens in my application code working locally. The JSON objects themselves are rendered in the DOM. 

(It's on codesandbox because play.mavo.io doesn't seem to allow me to include folders and remote `.json` files).

**Screenshot from Simple Test Case**

<img width="560" alt="Screen Shot 2021-11-29 at 5 46 05 PM" src="https://user-images.githubusercontent.com/69559/143955117-19e6ae15-20af-4810-a38a-c07e16bd7e86.png">

**Screenshot from My App, Same Behaviour**

<img width="1552" alt="Screen Shot 2021-11-26 at 10 21 48 PM" src="https://user-images.githubusercontent.com/69559/143955464-49f29095-0f82-4911-a4ba-dd70c1456273.png">

## Potential Root Cause

I did some debugging and tracked down the behaviour, it looks like [this case](https://github.com/mavoweb/mavo/blob/master/src/primitive.js#L1193-L1196) of the `format` static method in `primitives.js` is getting hit, and based on the comment `// Oops, we have an object. Print something more useful than [object Object]`
 it seems like that's a thing that shouldn't happen?

If the test-case above doesn't work, here's a listing of the simple test case files HTML:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Mavo Test</title>
    <link rel="stylesheet" href="https://get.mavo.io/mavo.css" />
    <script src="https://get.mavo.io/mavo.js"></script>
  </head>
  <body>
    <div mv-app="loadouts" mv-init="data/loadouts.json" mv-mode="read">
      <ul mv-list my-initial-items="0">
        <li class="character [name]" mv-list-item="loadout">
          <div class="title">[name]</div>
          <div class="portrait">
            <span class="help-text">Click a unit below</span>
          </div>
          <div class="allocated-max-stats">
            <span class="allocated">[allocated_stat_points]</span>/<spanclass="max">[max_stat_points]</span>
          </div>
        </li>
      </ul>
    </div>
  </body>
</html>
```

and a snippet of my `data/loadouts.json` file:

```json
{
  "loadout": [
    {
      "slot": 0,
      "name": "raidmaster",
      "type": "",
      "stats": "",
      "allocated_stat_points": 4,
      "max_stat_points": 11
    },
    {
      "slot": 1,
      "name": "basher",
      "type": "",
      "stats": "",
      "allocated_stat_points": 0,
      "max_stat_points": 0
    },
    ... etc
  ]
}
```

**Comment by DmitrySharabin** [comment]
Hi David! Welcome aboard. :)

The issue you are facing is a feature, not a bug. You can find more about it here: https://github.com/mavoweb/mavo/issues/692. Specifically, see point 6. Please feel free to take part in our discussions. We love and appreciate it. :)

Since we don't want too much magic in Mavo behavior, sometimes we expect authors to be as precise in their intentions as they can. Concerning your case, since you don't mark any elements _inside_ `<li>` (collection item) with the `property` attribute, Mavo doesn't consider it as a _group_ (i.e., an object in JS). So, when you refer to properties like `name` or `allocated_stat_points` inside expressions, Mavo doesn't understand what you mean. To fix this, you can give Mavo a hint by adding `mv-group` to `<li>`. Then, Mavo will interpret `name` and `allocated_stat_points` as _properties inside complex property_  (collection item) `loadout`.

Another way to get the same result is just by adding `property` attributes with the appropriate values to the corresponding elements instead of using expressions. If you like, you can add `property` to only one of them. It'll be sufficient for Mavo to understand that it needs to deal with a complex property (i.e., group).

I recreated your testcase on Codepen so you could take a look at what I mean: https://codepen.io/dmitrysharabin/pen/XWeWPvB.

And one more thing. I found a typo in this line: `<ul mv-list my-initial-items="0">`. Please use `mv-initial-items`, not `my-initial-items`. ;)

Hope my explanations make sense. Please feel free to ask any questions you might have. We are here to help. :)

**Comment by davemo** [comment]
Wow, thanks for the detailed writeup and for graciously correcting my mistakes. I really appreciate you taking the time @DmitrySharabin -- I will move forward now and keep on with my Mavo experiments. 💚
