### ISSUE TITLE
li & span editing doesn't work as expected

### ISSUE THREAD

**Issue by GalinhaLX** [mavoweb/mavo#807]
Hi,

[https://codepen.io/GATIGA/pen/bGoKdmr](url)

When trying to edit `<li>` or `<span>` element, it doesn't show all text

Works fine for `<h1>..<h5>, <div>` and `<p>`

I even tried to force it with :
```
 word-wrap: break-word;
word-break: break-all;
```

but can't find the way to make visible all line to edit

is this a bug?

(using Chrome & Safari on Mac)

**Comment by DmitrySharabin** [comment]
Hi there,

The issue you are facing is a feature, not a bug. :)

Mavo considers some elements as “block elements.” It's such elements as `p`, `div`, `dt`, `dd`, `h1`, `h2`, `h3`, `h4`, `h5`, `h6,` `article`, `section`, `address`, and `pre`. Depending on the styling (the `display` property to be more precise), Mavo edits such elements via either `<input>` or `<textarea>`. E.g., for elements with `display: inline-block;` Mavo uses `<input>`.

Some elements (e.g., `a`, `img`, `video`, `audio`, `meta`, etc.) are edited via popup. Some elements, that are not form elements themselves, are edited, via `<input>`. And so on, and so forth.

The elements you mentioned (`<li>` and `<span>`) are edited via `<input>`. And Mavo takes into account the styles you apply to those elements. So, in your case, if you need to see the whole line of text in edit mode, I would suggest adding `display: inline-block;` to `span` and `li`. However, please keep in mind that it might break your layout in edit mode.

As an alternative, I would suggest making properties not out of `<li>` themselves, but of `<p>`s inside them, like so:
```html
<li><p property="prop">Some long line of text</p></li>
```

Unfortunately, that won't work for `<span>`s since they can't have `<p>`s inside them (only [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#phrasing_content) is allowed inside `<span>`).

But it doesn't mean there's nothing we can do. We can still use a [custom editor](https://mavo.io/docs/properties#mv-editor) since Mavo UI is fully customizable. So if we want to edit our properties via `<textarea>` instead of `<input>`, we can do it. Like so:

```html
<div mv-app="customEditor">
	<p>		
		<span property="prop" mv-editor="#custom" mv-default>Foo</span>
	</p>
</div>

<textarea id="custom" hidden></textarea>
```

Hope it helps.

**Comment by joyously** [comment]
@DmitrySharabin perhaps you can improve the docs using this explanation.

**Comment by GalinhaLX** [comment]
Hi, thanks a lot for this answer.

it now works with those solutions

**Comment by LeaVerou** [comment]
> @DmitrySharabin perhaps you can improve the docs using this explanation.

Perhaps you could too!

**Comment by joyously** [comment]
> Perhaps you could too!

Perhaps, but documentation is better when written by someone who understands it.

**Comment by GalinhaLX** [comment]
Hi 
I totally understand the need to update the documentation, and I agree that all of us should contribute, but let me give you my impressions about it, as a simple user:

1/ when I click "edit this page with mavo", on FAQ page for exemple, it asks me to give access to all my github, including read and write to private folders. Well, if I put it private, it's because it's private :)
=> isn't there a way to you to ask less permissions?

2/ There's a huge work on documentation, done by people who know this dev, so I, as others, can sometimes be shy to publish something potentially wrong...
=> wouldn't be interesting to have a general FAQ, width a "draft" status (readable by all), with some kind of votes (people would vote, and it would be an indication that information is accurate), plus an "approved" status when reviewed by some of you?

3/ I don't know if its possible, but another option is maybe if there's a way to copy/paste good answers (Sorry, I'm new to Github) , in a simple folder under "issues", with a name like "SOLVED issues doc", as, I guess like many people, the first thing I do, is search on this folders for information

**Comment by GalinhaLX** [comment]
also found another idea: 
4/ add a new label "DOCUMENTATION" => i don't know if it's possible to label only one message (or in worst case a discussion) ,and inform about it in the main documentation page, to look here for this label

**Comment by GalinhaLX** [comment]
Closing topic, as it's not an issue
