### ISSUE TITLE
CSS: Style differently in edit mode , not real colors displayed

### ISSUE THREAD

**Issue by GalinhaLX** [mavoweb/mavo#816]
Hi,

While trying to set a background color following the documentation "Style differently in edit mode" from here:
[https://mavo.io/docs/ui#styling-with-css](https://mavo.io/docs/ui#styling-with-css)

I wasn't able to set real wanted color:
black is not black
white is not white

[https://codepen.io/GATIGA/pen/mdBZBJg](https://codepen.io/GATIGA/pen/mdBZBJg)

Is this a bug? or am I missing something?
(look likes it's affecting color on a parent element, not visible on my demo)

Regards

**Comment by LeaVerou** [comment]
When you're not sure why elements look the way they do, it often helps to right click and select "Inspect Element" to see what CSS is applying. In this case you'd also need to enable `:hover` and then you'll see what the offending rule is:

![image](https://user-images.githubusercontent.com/175836/150511357-755d4baf-aac5-40ff-88f4-cc743042abac.png)

This is the semi-transparent yellow that is used to show that elements are editable. It uses a `box-shadow` instead of a background to avoid getting in the way of existing CSS as much as possible. Of course, this doesn't work so well when you want to remove it 😄 
What you need to do is set `box-shadow: none` (or any other value). However, because of the high specificity of this selector (0,4,1), you need something with at least equally high specificity to override it. You can change your selector to `[property="name"][mv-mode="edit"]:hover:hover:hover` which has a specificity of 0,5,0 which is greater than 0,4,1 and it works.

Hope this helps!

As a side note, I cannot *wait* for `:where()` to be more widely supported so we can use it all over the Mavo CSS files. In fact, Mavo was what I had in mind when I proposed `:where()` to the CSS WG back in 2017. Actually, @DmitrySharabin would you say that time has come?

**Comment by DmitrySharabin** [comment]
> Actually, @DmitrySharabin would you say that time has come?

I believe it has. I advocate for Mavo to be a (_highly demanded_) library grounded on modern JS and CSS. I think we can afford it. 😊

Just a side note, what if we add some new custom properties to the existing ones (`--mv-mode`, `--mv-loader`, `--mv-rubbish-bin`)? I think it would be great if we could, e.g., change the shadow color for highlighted collection items, or the background color of popup messages, trash bin icon, etc.?

**Comment by GalinhaLX** [comment]
Thank you so much!
I didn't know that you could stack ":hover" : something that I don't understand here => but I'll search in CSS docs
Never 
I had no idea the 'trick' was in the shadows 


A usage note for users like me: 
Everything is called "mv-":
properties as well as classes, but sometimes I can make the mistake of putting classes as properties, or the reverse

Wouldn't it be possible to differentiate them by their name in the future?

mv-P-
mv-C-

**Comment by LeaVerou** [comment]
You can stack any CSS simple selector multiple times except element selectors, i.e. things like `.foo.foo.foo` or `:hover:hover:hover` or `#foo#foo#foo` or `[foo][foo][foo]` are all valid.

**Comment by GalinhaLX** [comment]
After burning many hours battling to apply styles to HTML (before learning about CSS specificity), that's an interesting CSS concept: some kind of "last chance" to apply it :)

I share here, a visual representation to play with: [https://specificity.keegan.st/](https://specificity.keegan.st/)

Thanks a lot @LeaVerou to share knowledge
