### ISSUE TITLE
mv-if conditional display of properties 

### ISSUE THREAD

**Issue by GalinhaLX** [mavoweb/mavo#832]
Hi

Using mv-if with properties from same storage data source with 3 elements (A, B, C):, 

when trying to display:
(A) _or_ (B & C) -> works
(A & B ) _or_ (C) -> works

When trying to display:
(A & **B**) _or_ (**B** & C) -> Doesn't work     (Note: (B) should be part of displayed result in both conditions)

Codepen: [https://codepen.io/galinhalx/pen/WNdgVWy](https://codepen.io/galinhalx/pen/WNdgVWy)

I'm I missing something on my code, or is this a bug?

Regards

**Comment by LeaVerou** [comment]
Hi @GalinhaLX,

Could you please simplify your codepen so that it's easier to see what the issue is? There is currently way too much in there that is not related to the problem at hand. Just a few divs showing the kind of mv-if that doesn't work, and the kind that does, plus a few spans to define the A, B, C properties.

Here are some good resources about reducing test cases:

https://webkit.org/test-case-reduction/
https://css-tricks.com/reduced-test-cases/

Thank you!

**Comment by GalinhaLX** [comment]
Hi 

Simplified codepen here: [https://codepen.io/galinhalx/pen/QWaZNoe](https://codepen.io/galinhalx/pen/QWaZNoe)

Thank you

**Comment by DmitrySharabin** [comment]
Hey there, @GalinhaLX,

The first thing I see here is that you define the `destination` property **twice** in one and the same app. That makes it an [implicit collection](https://mavo.io/docs/primer#mv-multiple), so the data you have in `storage2` doesn't match the structure you have in your app; there should be an _array of strings_ instead of _simple string_.

Try to switch to edit mode in the `app2`, give the `destination` property some value, and save it to see it yourself.

<img width="572" alt="Screen Shot 2022-04-14 at 17 40 46" src="https://user-images.githubusercontent.com/9166277/163415869-6b1e41a0-41cb-44fc-880a-c7218035e491.png">

So, one solution I see here is to replace one of the definitions of the `destination` property with its value in another part of the app either via expressions (e.g., `[destination]`) or via the `mv-value` attribute (e.g., `<div mv-value="destination"></div>`).

However, there is one thing that bothers me: when we have a property inside a code fragment that is removed from the DOM via `mv-if`, the value of this property is wiped out.

The reduced testcase: https://codepen.io/dmitrysharabin/pen/NWXOgVr

@LeaVerou, any thoughts on why this happens? Is it a bug?

**Comment by LeaVerou** [comment]
> However, there is one thing that bothers me: when we have a property inside a code fragment that is removed from the DOM via mv-if, the value of this property is wiped out so that we can't use it in expressions.

That is by design. If you just want to hide it and keep its data around for expressions, you can use the `hidden` HTML attribute with an expression.

**Comment by LeaVerou** [comment]
Why not use a single destination property with `condition1 or condition2` in `mv-if`?

**Comment by GalinhaLX** [comment]
Maybe better to write my use case: I'm doing a small site builder

concept:
Left panel I have checkboxes which activates "html blocs" in a right side (a hero section for example)

Right side, I can edit properties of this hero section, like title, subtitle, href

-> Now, I want to be able to propose different hero sections, but connected to same properties (same fields in database)

Hero1: title, subtitle, href
Hero2: title, href
Hero3: title, color

As you cans see, some properties are common, others are new.

But I want to be able to change the html section, while properties refers to same database fields
(so user can edit its fields in different Hero sections, but it will always bind to the same data field

**Example**: I can modify title in Hero 1, and I will see it display in Hero 2 or Hero 3

**Comment by GalinhaLX** [comment]
> Why not use a single destination property with `condition1 or condition2` in `mv-if`?

Can you please detail your idea @LeaVerou , I'm not sure to understand

**Comment by DmitrySharabin** [comment]
I came up with this workaround—fake editing in two places. Please, have a look. Is that what you were talking about?

https://codepen.io/dmitrysharabin/pen/LYegONe

**Comment by GalinhaLX** [comment]
Thanks @DmitrySharabin 

Suits my needs
