### ISSUE TITLE
'import' button displayed when logged out on mavo bar

### ISSUE THREAD

**Issue by GalinhaLX** [mavoweb/mavo#838]
Hi

in this [case](https://codepen.io/galinhalx/pen/KKZjjKM?editors=1100),

while user is not logged in, mavo displays "login" & ..."**import**" buttons

(Even  if it can be hidden with 'no-import',
that sounds strange that a user could upload another version of website , even locally without being logged

is this a bug?

if it isn't a bug:
-how to change 'no-import' (when logged out)        to   'import' (when logged in)?

**Comment by DmitrySharabin** [comment]
> how to change 'no-import' (when logged out) to 'import' (when logged in)?

I would follow the way to [customize the UI](https://mavo.io/docs/ui#styling-with-css) suggested in the docs. E.g., the following CSS rule should work:

```css
[mv-app][mv-permissions~="login"] .mv-bar.mv-ui .mv-import {
	display: none;
}
```

> that sounds strange that a user could upload another version of website , even locally without being logged

I believe this is done intentionally (by design): other users can easily re-use your app simply by providing (or pointing to) their data. Moreover, even if you hide the `import` button from logged-out users (see above), one can easily use your app with their data via URL. See https://mavo.io/docs/storage#url-params for details. For me, this is one of the coolest features Mavo has. :)

**Comment by GalinhaLX** [comment]
Thank you for your answer @DmitrySharabin 

I agree that mavo is great to propose for users to have their own data uploaded,
but it stills sounds a little be strange (for me and my [🐱](https://emojipedia.org/cat-face/)) that this "import" is displayed by default

I would put it the opposite way:
hidden by default, with the ability to add "with import" :)
