### ISSUE TITLE
[Documentation] Readme can be improved more

### ISSUE THREAD

**Issue by sudhanshutech** [mavoweb/mavo#951]
**Readmes** are a first attraction for any contributors so it could be more better.

**Comment by sudhanshutech** [comment]
I will be really grateful to **contribute**. Can you **assign** me this?

**Comment by LeaVerou** [comment]
We only assign issues to longtime contributors, not people new to the project. If you feel you have improvements for the readme, feel free to open a pull request. I will close this issue since it's vague and does not point out anything specific. Anything can be improved further and nothing is perfect, but we don't open issues saying precisely that.
