### ISSUE TITLE
Backend put method being called with stale serialized data

### ISSUE THREAD

**Issue by jon-p-moore** [mavoweb/mavo#962]
I am mostly a back-end developer, looking for something to use for quick prototyping.  I don't know a lot of Javascript - enough to get myself into trouble.  I have been trying to get a simple Mavo list working against some of our back-end REST APIs by writing a minimal backend to wrap the API calls, but calls to the back-end API have not been including any data updates made by editing the data in the page.

I've reduced things to the minimal test case below.  The Github backend works fine for me, so I think there must be something I need to do that I'm missing.  The page below loads a list from a hard-coded array.  I then manually edit the list in the page - for example, replacing the name "item 2" with "modified item 2".  When I then click the Save button, the `serialized` parameter passed to the `put()` method is logged, and it's always the old data, without the modifications I've made.  (This happens whether or not I finish editing by clicking the Edit button again, and it's the same in the latest Windows versions of both Firefox and Edge)

I was expecting that if I edited the data in the list, the edited version would be passed to the backend.  I've looked through the Github backend code (as well as my limited JS knowledge allows), for anything I could be missing, and can't find anything.

What should I be doing so that the `put(serialized)` call is passed the data with the edits I've made in the UI?  Or am I misunderstanding how the update should work?  Pointers will be gratefully received.

```
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://get.mavo.io/mavo.css"/>
        <script src="https://get.mavo.io/mavo.js"></script>
        <script>
            // Simple backend for testing Mavo.
            Mavo.Backend.register(class PGObject extends Mavo.Backend {
                id = "Debugging"

                constructor (url, o) {
                    let realUrl = url.substring(5);
                    console.log("Building backend for URL " + realUrl);
                    super(realUrl, o);
                    this.permissions.on(["read", "edit", "save"]);
                    this.constructor.useCache = false;
                    this.cachedData = 
                            JSON.stringify(
                                Array.of(
                                    {id:'1', name:'item 1'},
                                    {id:'2', name:'item 2'}
                                )
                            );
                }

                async get (url = new URL(this.url)) {
                    console.log("Getting backend data." + this.cachedData);
                    return this.cachedData;
                }

                async put (serialized, path) {
                    console.log("Putting data " + serialized);
                    this.cachedData = serialized;
                    return serialized;
                }

                static test (value) {
                    console.log("Testing "+ value);
                    return value.startsWith('test:');
                }
            });
        </script>
    </head>
    <body>
        <div mv-app="testlist" mv-storage="test:foo">
            <ul mv-list>
                <li mv-list-item>
                    <span property="id"></span> <span property="name"></span>
                </li>
            </ul>
        </div>
    </body>
</html>
```

**Comment by DmitrySharabin** [comment]
Hey @jon-p-moore,

I'll do my best to explain why this happens and suggest a possible solution.

In your app, you have an _unnamed_ collection of items. Even though you didn't provide a name for it (neither `mv-list` nor `mv-list-item` doesn't have a value), Mavo will give it a default name; in this case, it will be `item`. So, according to the structure of your app, Mavo expects to get data with the following format: `{ item: [{id: ..., name: ...}, {id: ..., name: ...}, ...] }`.

When you pass an array, instead of the expected object, to Mavo, Mavo does its best to find in the app an appropriate place for it. And it finds the `item` collection. So even though you see what you expected to see, internally, Mavo is working with an array of two elements (`[{id: 1, name: "item 1"}, {id: 2, name: "item 2"}]`), and this array additionally has the `item` property (since arrays are objects in JavaScript) with value `[{id: 1, name: "item 1"}, {id: 2, name: "item 2"}]`.

<img width="692" alt="image" src="https://github.com/mavoweb/mavo/assets/9166277/651bda6e-860c-423c-9269-003c80551620">

And when you edit the list on the page, you edit items inside the array, which is the value of the `item` property. Not the items you passed to Mavo.

<img width="314" alt="image" src="https://github.com/mavoweb/mavo/assets/9166277/618af784-65de-45cb-b09d-8e517e2e7b19">

And finally, the `put()` method gets the data, serialized (by default) with `JSON.stringify()`. And what exactly is being stringified? An array. But only the values of its _numeric_ properties—the source items that have not been changed. That's why we don't see the changes we make.

So, I suggest you transform the data before passing it to Mavo. E.g., you can pass an object with the `item` property, like so: `{ item: [<Array_returned_from_your_API>] }`. However, before returning updated data to your backend, you should get its `item` property (you should probably implement the `store()` method instead of `put()` to avoid serialization).

I hope my explanation makes sense. If not, please feel free to ask for any clarification.

**Comment by jon-p-moore** [comment]
Thanks, @DmitrySharabin.

Following the above, I changed the hard-coded data to
```
                            JSON.stringify(
                                {
                                    "item" :
                                    Array.of(
                                        {id:'1', name:'item 1'},
                                        {id:'2', name:'item 2'})
                                });
```
and it worked, with the JSON coming back with modifications, as expected.

If I then change "item" in the data to something I define myself and tinker with the HTML:
```
            <ul mv-list=A>
                <li mv-list-item=B>
```
If either A or B is set, then things work.  If A and B are set to different values, then A is used and B ignored.

I shall build this back up and get the API calls working.  I shall look at the `store` method, too.
